### ISSUE TITLE
Is it supposed to just say "Sync Error"?

### ISSUE THREAD

**Issue by Ruikio** [stiefeljackal/JworkzNeosFixFrickenSync#3]
Is this how I know it's doing anything besides doing stuff in the log file? Will the red Sync Error! text go away if it successfully finishes the sync? 

The % in the logs is no longer updating. There doesn't seem to be a lot of clarity if the mod is doing anything which is a little concerning. I don't know if I should sit here for 30 more minutes or restart to see if it does anything again.

**Comment by stiefeljackal** [comment]
Thank you for submitting your issue!

> Is this how I know it's doing anything besides doing stuff in the log file? Will the red Sync Error! text go away if it successfully finishes the sync?

So the mod fixes a bug in Neos where syncs that fail or throw an exception will cause the sync loop to stop. Hence, when that happens, you get a stuck sync (the 0% or 10% light blue syncing message that doesn't seem to do anything). When a stuck sync occurs, any syncing tasks before that will not initiate at all. The red **Sync Error!** that you see is actually a feature of Neos that appears when the sync queue finishes with at least one or more sync errors. With Neos's current implementation, this message does not go away. Since I wanted this mod to follow Neos's syncing process as much as possible and there is no recording keeping of failed syncs, this message will always show no matter if the next queue of sync tasks are all successful. That is why I am currently making an add-on mod that will address this confusing behavior.

> The % in the logs is no longer updating. There doesn't seem to be a lot of clarity if the mod is doing anything which is a little concerning. I don't know if I should sit here for 30 more minutes or restart to see if it does anything again.

The mod addresses error and exception handling to prevent the sync loop from stopping. However, the comment about the logs exhibiting this behavior is concerning. May I see the log file?

**Comment by stiefeljackal** [comment]
There is now a separate mod that will display your sync tasks and will allow you to act on failed tasks. For conflicting records, you will be able to force sync, delete unsynced, or keep both within VR. For any other failed sync tasks, you can either retry the task or delete the unsynced task.

https://github.com/stiefeljackal/JworkzNeosFixFrickenSync.Client

For the logging, that should be addressed in the latest v2 and v1 of the mod.

**Comment by stiefeljackal** [comment]
Closed as resolved in [https://github.com/stiefeljackal/JworkzNeosFixFrickenSync.Client](https://github.com/stiefeljackal/JworkzNeosFixFrickenSync.Client).
